subsonic-main/src/main/java/net/sourceforge/subsonic/domain/SearchResult.java
/*
 This file is part of Subsonic.

 Subsonic is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Subsonic is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Subsonic.  If not, see <http://www.gnu.org/licenses/>.

 Copyright 2009 (C) Sindre Mehus
 */
package net.sourceforge.subsonic.domain;

import java.util.ArrayList;
import java.util.List;

import net.sourceforge.subsonic.service.MediaScannerService;
import net.sourceforge.subsonic.service.SearchService;

/**
 * The outcome of a search.
 *
 * @author Sindre Mehus
 * @see SearchService#search
 */
public class SearchResult {

    private final List<MediaFile> mediaFiles = new ArrayList<MediaFile>();
    private final List<Artist> artists = new ArrayList<Artist>();
    private final List<Album> albums = new ArrayList<Album>();

    private int offset;
    private int totalHits;

    public List<MediaFile> getMediaFiles() {
        return mediaFiles;
    }

    public List<Artist> getArtists() {
        return artists;
    }

    public List<Album> getAlbums() {
        return albums;
    }

    public int getOffset() {
        return offset;
    }

    public void setOffset(int offset) {
        this.offset = offset;
    }

      public int getTotalHits() {
        return totalHits;
    }

    public void setTotalHits(int totalHits) {
        this.totalHits = totalHits;
    }
}

subsonic-main/src/main/java/net/sourceforge/subsonic/domain/User.java
/*
 This file is part of Subsonic.

 Subsonic is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Subsonic is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Subsonic.  If not, see <http://www.gnu.org/licenses/>.

 Copyright 2009 (C) Sindre Mehus
 */
package net.sourceforge.subsonic.domain;

/**
 * Represent a user.
 *
 * @author Sindre Mehus
 */
public class User {

    public static final String USERNAME_ADMIN = "admin";

    private final String username;
    private String password;
    private String email;
    private boolean ldapAuthenticated;
    private long bytesStreamed;
    private long bytesDownloaded;
    private long bytesUploaded;

    private boolean isAdminRole;
    private boolean isSettingsRole;
    private boolean isDownloadRole;
    private boolean isUploadRole;
    private boolean isPlaylistRole;
    private boolean isCoverArtRole;
    private boolean isCommentRole;
    private boolean isPodcastRole;
    private boolean isStreamRole;
    private boolean isJukeboxRole;
    private boolean isShareRole;

    public User(String username, String password, String email, boolean ldapAuthenticated,
                long bytesStreamed, long bytesDownloaded, long bytesUploaded) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.ldapAuthenticated = ldapAuthenticated;
        this.bytesStreamed = bytesStreamed;
        this.bytesDownloaded = bytesDownloaded;
        this.bytesUploaded = bytesUploaded;
    }

    public User(String username, String password, String email) {
        this(username, password, email, false, 0, 0, 0);
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public boolean isLdapAuthenticated() {
        return ldapAuthenticated;
    }

    public void setLdapAuthenticated(boolean ldapAuthenticated) {
        this.ldapAuthenticated = ldapAuthenticated;
    }

    public long getBytesStreamed() {
        return bytesStreamed;
    }

    public void setBytesStreamed(long bytesStreamed) {
        this.bytesStreamed = bytesStreamed;
    }

    public long getBytesDownloaded() {
        return bytesDownloaded;
    }

    public void setBytesDownloaded(long bytesDownloaded) {
        this.bytesDownloaded = bytesDownloaded;
    }

    public long getBytesUploaded() {
        return bytesUploaded;
    }

    public void setBytesUploaded(long bytesUploaded) {
        this.bytesUploaded = bytesUploaded;
    }

    public boolean isAdminRole() {
        return isAdminRole;
    }

    public void setAdminRole(boolean isAdminRole) {
        this.isAdminRole = isAdminRole;
    }

    public boolean isSettingsRole() {
        return isSettingsRole;
    }

    public void setSettingsRole(boolean isSettingsRole) {
        this.isSettingsRole = isSettingsRole;
    }

    public boolean isCommentRole() {
        return isCommentRole;
    }

    public void setCommentRole(boolean isCommentRole) {
        this.isCommentRole = isCommentRole;
    }

    public boolean isDownloadRole() {
        return isDownloadRole;
    }

    public void setDownloadRole(boolean isDownloadRole) {
        this.isDownloadRole = isDownloadRole;
    }

    public boolean isUploadRole() {
        return isUploadRole;
    }

    public void setUploadRole(boolean isUploadRole) {
        this.isUploadRole = isUploadRole;
    }

    public boolean isPlaylistRole() {
        return isPlaylistRole;
    }

    public void setPlaylistRole(boolean isPlaylistRole) {
        this.isPlaylistRole = isPlaylistRole;
    }

    public boolean isCoverArtRole() {
        return isCoverArtRole;
    }

    public void setCoverArtRole(boolean isCoverArtRole) {
        this.isCoverArtRole = isCoverArtRole;
    }

    public boolean isPodcastRole() {
        return isPodcastRole;
    }

    public void setPodcastRole(boolean isPodcastRole) {
        this.isPodcastRole = isPodcastRole;
    }

    public boolean isStreamRole() {
        return isStreamRole;
    }

    public void setStreamRole(boolean streamRole) {
        isStreamRole = streamRole;
    }

    public boolean isJukeboxRole() {
        return isJukeboxRole;
    }

    public void setJukeboxRole(boolean jukeboxRole) {
        isJukeboxRole = jukeboxRole;
    }

    public boolean isShareRole() {
        return isShareRole;
    }

    public void setShareRole(boolean shareRole) {
        isShareRole = shareRole;
    }

    @Override
    public String toString() {
        StringBuffer result = new StringBuffer(username);

        if (isAdminRole) {
            result.append(" [admin]");
        }
        if (isSettingsRole) {
            result.append(" [settings]");
        }
        if (isDownloadRole) {
            result.append(" [download]");
        }
        if (isUploadRole) {
            result.append(" [upload]");
        }
        if (isPlaylistRole) {
            result.append(" [playlist]");
        }
        if (isCoverArtRole) {
            result.append(" [coverart]");
        }
        if (isCommentRole) {
            result.append(" [comment]");
        }
        if (isPodcastRole) {
            result.append(" [podcast]");
        }
        if (isStreamRole) {
            result.append(" [stream]");
        }
        if (isJukeboxRole) {
            result.append(" [jukebox]");
        }
        if (isShareRole) {
            result.append(" [share]");
        }

        return result.toString();
    }
}

subsonic-main/src/main/java/net/sourceforge/subsonic/controller/PlaylistController.java
/*
 This file is part of Subsonic.

 Subsonic is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Subsonic is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Subsonic.  If not, see <http://www.gnu.org/licenses/>.

 Copyright 2009 (C) Sindre Mehus
 */
package net.sourceforge.subsonic.controller;

import net.sourceforge.subsonic.domain.Playlist;
import net.sourceforge.subsonic.domain.User;
import net.sourceforge.subsonic.domain.UserSettings;
import net.sourceforge.subsonic.service.PlaylistService;
import net.sourceforge.subsonic.service.SecurityService;
import net.sourceforge.subsonic.service.SettingsService;
import org.springframework.web.bind.ServletRequestUtils;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.ParameterizableViewController;
import org.springframework.web.servlet.view.RedirectView;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.HashMap;
import java.util.Map;

/**
 * Controller for the main page.
 *
 * @author Sindre Mehus
 */
public class PlaylistController extends ParameterizableViewController {

    private SecurityService securityService;
    private PlaylistService playlistService;
    private SettingsService settingsService;

    @Override
    protected ModelAndView handleRequestInternal(HttpServletRequest request, HttpServletResponse response) throws Exception {
        Map<String, Object> map = new HashMap<String, Object>();

        int id = ServletRequestUtils.getRequiredIntParameter(request, "id");
        User user = securityService.getCurrentUser(request);
        String username = user.getUsername();
        UserSettings userSettings = settingsService.getUserSettings(username);
        Playlist playlist = playlistService.getPlaylist(id);
        if (playlist == null) {
            return new ModelAndView(new RedirectView("notFound.view"));
        }

        map.put("playlist", playlist);
        map.put("user", user);
        map.put("editAllowed", username.equals(playlist.getUsername()) || securityService.isAdmin(username));
        map.put("partyMode", userSettings.isPartyModeEnabled());

        ModelAndView result = super.handleRequestInternal(request, response);
        result.addObject("model", map);
        return result;
    }

    public void setSecurityService(SecurityService securityService) {
        this.securityService = securityService;
    }

    public void setPlaylistService(PlaylistService playlistService) {
        this.playlistService = playlistService;
    }

    public void setSettingsService(SettingsService settingsService) {
        this.settingsService = settingsService;
    }
}

subsonic-main/src/main/java/net/sourceforge/subsonic/controller/SearchController.java
/*
 This file is part of Subsonic.

 Subsonic is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Subsonic is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Subsonic.  If not, see <http://www.gnu.org/licenses/>.

 Copyright 2009 (C) Sindre Mehus
 */
package net.sourceforge.subsonic.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.springframework.validation.BindException;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.SimpleFormController;

import net.sourceforge.subsonic.command.SearchCommand;
import net.sourceforge.subsonic.domain.SearchCriteria;
import net.sourceforge.subsonic.domain.SearchResult;
import net.sourceforge.subsonic.domain.User;
import net.sourceforge.subsonic.domain.UserSettings;
import net.sourceforge.subsonic.service.PlayerService;
import net.sourceforge.subsonic.service.SecurityService;
import net.sourceforge.subsonic.service.SettingsService;
import net.sourceforge.subsonic.service.SearchService;

/**
 * Controller for the search page.
 *
 * @author Sindre Mehus
 */
public class SearchController extends SimpleFormController {

    private static final int MATCH_COUNT = 25;

    private SecurityService securityService;
    private SettingsService settingsService;
    private PlayerService playerService;
    private SearchService searchService;

    @Override
    protected Object formBackingObject(HttpServletRequest request) throws Exception {
        return new SearchCommand();
    }

    @Override
    protected ModelAndView onSubmit(HttpServletRequest request, HttpServletResponse response, Object com, BindException errors)
            throws Exception {
        SearchCommand command = (SearchCommand) com;

        User user = securityService.getCurrentUser(request);
        UserSettings userSettings = settingsService.getUserSettings(user.getUsername());
        command.setUser(user);
        command.setPartyModeEnabled(userSettings.isPartyModeEnabled());

        String any = StringUtils.trimToNull(command.getQuery());

        if (any != null) {

            SearchCriteria criteria = new SearchCriteria();
            criteria.setCount(MATCH_COUNT);
            criteria.setQuery(any);

            SearchResult artists = searchService.search(criteria, SearchService.IndexType.ARTIST);
            command.setArtists(artists.getMediaFiles());

            SearchResult albums = searchService.search(criteria, SearchService.IndexType.ALBUM);
            command.setAlbums(albums.getMediaFiles());

            SearchResult songs = searchService.search(criteria, SearchService.IndexType.SONG);
            command.setSongs(songs.getMediaFiles());

            command.setPlayer(playerService.getPlayer(request, response));
        }

        return new ModelAndView(getSuccessView(), errors.getModel());
    }

    public void setSecurityService(SecurityService securityService) {
        this.securityService = securityService;
    }

    public void setSettingsService(SettingsService settingsService) {
        this.settingsService = settingsService;
    }

    public void setPlayerService(PlayerService playerService) {
        this.playerService = playerService;
    }

    public void setSearchService(SearchService searchService) {
        this.searchService = searchService;
    }
}

subsonic-main/src/main/java/net/sourceforge/subsonic/controller/SettingsController.java
/*
 This file is part of Subsonic.

 Subsonic is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Subsonic is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Subsonic.  If not, see <http://www.gnu.org/licenses/>.

 Copyright 2009 (C) Sindre Mehus
 */
package net.sourceforge.subsonic.controller;

import net.sourceforge.subsonic.domain.*;
import net.sourceforge.subsonic.service.*;
import org.springframework.web.servlet.*;
import org.springframework.web.servlet.view.*;
import org.springframework.web.servlet.mvc.*;

import javax.servlet.http.*;

/**
 * Controller for the main settings page.
 *
 * @author Sindre Mehus
 */
public class SettingsController extends AbstractController {

    private SecurityService securityService;


    protected ModelAndView handleRequestInternal(HttpServletRequest request, HttpServletResponse response) throws Exception {

        User user = securityService.getCurrentUser(request);

        // Redirect to music folder settings if admin.
        String view = user.isAdminRole() ? "musicFolderSettings.view" : "personalSettings.view";

        return new ModelAndView(new RedirectView(view));
     }

    public void setSecurityService(SecurityService securityService) {
        this.securityService = securityService;
    }
}

subsonic-main/src/main/webapp/WEB-INF/jsp/wap/browse.jsp
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wml PUBLIC "-//WAPFORUM//DTD WML 1.1//EN" "http://www.wapforum.org/DTD/wml_1.1.xml">

<%@ page language="java" contentType="text/vnd.wap.wml; charset=utf-8" pageEncoding="iso-8859-1"%>

<wml>

    <%@ include file="head.jsp" %>

    <card id="main" title="Subsonic" newcontext="false">

        <p><small><b>

            <sub:url value="/wap/playlist.view" var="playUrl">
                <sub:param name="play" value="${model.parent.path}"/>
            </sub:url>
            <sub:url value="/wap/playlist.view" var="addUrl">
                <sub:param name="add" value="${model.parent.path}"/>
            </sub:url>
            <sub:url value="/wap/download.view" var="downloadUrl">
                <sub:param name="path" value="${model.parent.path}"/>
            </sub:url>

            <c:choose>
                <c:when test="${fn:length(model.children) eq 1 and model.children[0].file}">
                    <a href="${playUrl}">[<fmt:message key="wap.browse.playone"/>]</a><br/>
                    <a href="${addUrl}">[<fmt:message key="wap.browse.addone"/>]</a><br/>
                    <c:if test="${model.user.downloadRole}">
                        <a href="${downloadUrl}">[<fmt:message key="wap.browse.downloadone"/>]</a><br/>
                    </c:if>
                </c:when>
                <c:otherwise>
                    <a href="${playUrl}">[<fmt:message key="wap.browse.playall"/>]</a><br/>
                    <a href="${addUrl}">[<fmt:message key="wap.browse.addall"/>]</a><br/>
                    <c:if test="${model.user.downloadRole}">
                        <a href="${downloadUrl}">[<fmt:message key="wap.browse.downloadall"/>]</a><br/>
                    </c:if>
                </c:otherwise>
            </c:choose>

            <a href="<c:url value="/wap/index.view"/>">[<fmt:message key="common.home"/>]</a><br/>
        </b></small></p>

        <p><small>

            <c:forEach items="${model.children}" var="child">
                <sub:url value="/wap/browse.view" var="browseUrl">
                    <sub:param name="path" value="${child.path}"/>
                </sub:url>
                <a href="${browseUrl}">${fn:escapeXml(child.title)}</a><br/>
            </c:forEach>

        </small></p>
    </card>
</wml>


subsonic-main/src/main/webapp/WEB-INF/jsp/wap/head.jsp
<%@ include file="../include.jsp" %>

<head>
    <meta http-equiv="Cache-Control" content="max-age=0" forua="true"/>
    <meta http-equiv="Cache-Control" content="must-revalidate" forua="true"/>
</head>

<template>
    <do type="prev" name="back" label="<fmt:message key="common.back"/>"><prev/></do>
</template>

subsonic-main/src/main/webapp/WEB-INF/jsp/wap/index.jsp
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wml PUBLIC "-//WAPFORUM//DTD WML 1.1//EN" "http://www.wapforum.org/DTD/wml_1.1.xml">

<%@ page language="java" contentType="text/vnd.wap.wml; charset=utf-8" pageEncoding="iso-8859-1" %>

<wml>

    <%@ include file="head.jsp" %>

    <card id="main" title="Subsonic" newcontext="false">
        <p>
            <small>

                <c:choose>
                <c:when test="${empty model.artists}">

                <b>
                    <a href="<c:url value="/wap/playlist.view"/>">[<fmt:message key="wap.index.playlist"/>]</a>
                </b>
                <br/>
                <b>
                    <a href="<c:url value="/wap/search.view"/>">[<fmt:message key="wap.index.search"/>]</a>
                </b>
                <br/>
                <b>
                    <a href="<c:url value="/wap/settings.view"/>">[<fmt:message key="wap.index.settings"/>]</a>
                </b>
                <br/>
            </small>
        </p>
        <p>
            <small>
                <c:forEach items="${model.indexes}" var="index">
                    <sub:url var="url" value="/wap/index.view">
                        <sub:param name="index" value="${index.index}"/>
                    </sub:url>
                    <a href="${url}">${index.index}</a>
                </c:forEach>
                </c:when>

                <c:otherwise>
                    <c:forEach items="${model.artists}" var="artist">
                        <c:forEach items="${artist.musicFiles}" var="mediaFile">
                            <sub:url var="url" value="/wap/browse.view">
                                <sub:param name="path" value="${mediaFile.path}"/>
                            </sub:url>
                            <a href="${url}">${fn:escapeXml(mediaFile.title)}</a>
                            <br/>
                        </c:forEach>
                    </c:forEach>
                </c:otherwise>
                </c:choose>

                <c:if test="${model.noMusic}">
                    <fmt:message key="wap.index.missing"/>
                </c:if>

            </small>
        </p>
    </card>
</wml>


subsonic-main/src/main/webapp/WEB-INF/jsp/wap/loadPlaylist.jsp
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wml PUBLIC "-//WAPFORUM//DTD WML 1.1//EN" "http://www.wapforum.org/DTD/wml_1.1.xml">

<%@ page language="java" contentType="text/vnd.wap.wml; charset=utf-8" pageEncoding="iso-8859-1"%>

<wml>

    <%@ include file="head.jsp" %>

    <card id="main" title="Subsonic" newcontext="false">
        <p><small>

            <c:forEach items="${model.playlists}" var="playlist">
                <sub:url var="url" value="/wap/playlist.view">
                    <sub:param name="load" value="${playlist.id}"/>
                </sub:url>
                <b><a href="${url}">${fn:escapeXml(playlist.name)}</a></b><br/>
            </c:forEach>
        </small></p>

    </card>
</wml>


subsonic-main/src/main/webapp/WEB-INF/jsp/wap/playlist.jsp
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wml PUBLIC "-//WAPFORUM//DTD WML 1.1//EN" "http://www.wapforum.org/DTD/wml_1.1.xml">

<%@ page language="java" contentType="text/vnd.wap.wml; charset=utf-8" pageEncoding="iso-8859-1"%>

<wml>

    <%@ include file="head.jsp" %>

    <c:if test="${fn:length(model.players) eq 1}">
        <c:choose>
            <c:when test="${empty model.players[0].name}">
                <c:set var="playerName" value=" - Player ${model.players[0].id}"/>
            </c:when>
            <c:otherwise>
                <c:set var="playerName" value=" - ${model.players[0].name}"/>
            </c:otherwise>
        </c:choose>
    </c:if>


    <card id="main" title="Subsonic" newcontext="false">
        <p><small><b><fmt:message key="wap.playlist.title"/>${playerName}</b></small></p>
        <p><small>

            <c:choose>
            <c:when test="${empty model.players}">
                <fmt:message key="wap.playlist.noplayer"/>
            </c:when>
                <c:otherwise>
                <b><a href="<c:url value="/wap/index.view"/>">[<fmt:message key="common.home"/>]</a></b><br/>
                <b><a href="<c:url value="/wap/loadPlaylist.view"/>">[<fmt:message key="wap.playlist.load"/>]</a></b><br/>
                <b><a href="<c:url value="/wap/playlist.view?random"/>">[<fmt:message key="wap.playlist.random"/>]</a></b><br/>

                <c:set var="playlist" value="${model.players[0].playlist}"/>

                <c:if test="${not empty playlist.files}">
                <b><a href="<c:url value="/play.m3u"/>">[<fmt:message key="wap.playlist.play"/>]</a></b><br/>
                <b><a href="<c:url value="/wap/playlist.view?clear"/>">[<fmt:message key="wap.playlist.clear"/>]</a></b><br/>
        </small></p>
        <p><small>

            <c:forEach items="${playlist.files}" var="file" varStatus="loopStatus">
                <c:set var="isCurrent" value="${(file eq playlist.currentFile) and (loopStatus.count - 1 eq playlist.index)}"/>
                ${isCurrent ? "<b>" : ""}
                <a href="<c:url value="/wap/playlist.view?skip=${loopStatus.count - 1}"/>">${fn:escapeXml(file.title)}</a>
                ${isCurrent ? "</b>" : ""}
                <br/>
            </c:forEach>
            </c:if>
            </c:otherwise>
            </c:choose>
        </small></p>
    </card>
</wml>


subsonic-main/src/main/webapp/WEB-INF/jsp/wap/search.jsp
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wml PUBLIC "-//WAPFORUM//DTD WML 1.1//EN" "http://www.wapforum.org/DTD/wml_1.1.xml">

<%@ page language="java" contentType="text/vnd.wap.wml; charset=utf-8" pageEncoding="iso-8859-1"%>

<wml>
    <%@ include file="head.jsp" %>
    <card id="main" title="Subsonic" newcontext="false">
        <p>
            <input name="query" value="" size="10"/>
            <anchor><fmt:message key="wap.search.title"/>
                <go href="<c:url value="/wap/searchResult.view"/>" method="get">
                    <postfield name="query" value="$query"/>
                </go>
            </anchor>
        </p>
    </card>
</wml>


subsonic-main/src/main/webapp/WEB-INF/jsp/wap/searchResult.jsp
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wml PUBLIC "-//WAPFORUM//DTD WML 1.1//EN" "http://www.wapforum.org/DTD/wml_1.1.xml">

<%@ page language="java" contentType="text/vnd.wap.wml; charset=utf-8" pageEncoding="iso-8859-1"%>

<wml>

    <%@ include file="head.jsp" %>
    <card id="main" title="Subsonic" newcontext="false">
        <p><small>

            <c:choose>
                <c:when test="${model.creatingIndex}">
                    <fmt:message key="wap.searchresult.index"/>
                </c:when>

                <c:otherwise>
                    <c:forEach items="${model.hits}" var="hit">
                        <sub:url var="url" value="/wap/browse.view">
                            <sub:param name="path" value="${hit.path}"/>
                        </sub:url>
                        <a href="${url}">${fn:escapeXml(hit.title)}</a><br/>
                    </c:forEach>
                </c:otherwise>
            </c:choose>
        </small></p>
    </card>

</wml>


subsonic-main/src/main/webapp/WEB-INF/jsp/wap/settings.jsp
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wml PUBLIC "-//WAPFORUM//DTD WML 1.1//EN" "http://www.wapforum.org/DTD/wml_1.1.xml">

<%@ page language="java" contentType="text/vnd.wap.wml; charset=utf-8" pageEncoding="iso-8859-1"%>

<wml>

    <%@ include file="head.jsp" %>
    <card id="main" title="Subsonic" newcontext="false">
        <p><small>
            <b><a href="<c:url value="/wap/index.view"/>">[<fmt:message key="common.home"/>]</a><br/></b>
            <b><a href="#player">[<fmt:message key="wap.settings.selectplayer"/>]</a></b>
        </small></p>
    </card>

    <card id="player" title="Subsonic" newcontext="false">
        <p><small>

            <b><a href="<c:url value="/wap/index.view"/>">[<fmt:message key="common.home"/>]</a><br/></b>
        </small></p><p><small>

        <c:choose>
            <c:when test="${empty model.playerId}">
                <fmt:message key="wap.settings.allplayers"/>
            </c:when>
            <c:otherwise>
                <a href="<c:url value="/wap/selectPlayer.view"/>"><fmt:message key="wap.settings.allplayers"/></a>
            </c:otherwise>
        </c:choose>
        <br/>

        <c:forEach items="${model.players}" var="player">
            <c:choose>
                <c:when test="${player.id eq model.playerId}">
                    ${player}
                </c:when>
                <c:otherwise>
                    <a href="<c:url value="/wap/selectPlayer.view?playerId=${player.id}"/>">${player}</a>
                </c:otherwise>
            </c:choose>
            <br/>
        </c:forEach>
    </small></p>
    </card>

</wml>
